### PR TITLE
Added rest api

### PR DESCRIPTION
**Pull request by johnsonkuang**
New feature:
- Serializes talks and publications objects currently (can add more objects to the serializer if necessary)
- Allows for POST and GET requests to the api
- Displays the data in a readable manner
### API form
[Image from Gyazo](https://gyazo.com/a00e71c60878fc099786bf6c619ab91b)
### JSON form
[Image from Gyazo](https://gyazo.com/8f37bc53fa594745662b8f700c944c90)

### CODE REVIEW

**Comment by johnsonkuang** [comment]
All changes suggested have been made.

**Comment by jonfroehlich** [comment]
Oops. Looks like you want to take out the import python code here so that there is clean separation in PRs as discussed.

**Comment by johnsonkuang** [comment]
changes made.

**Comment by johnsonkuang** [comment]
changes made, please merge. Thank you.

**Pull request merged**
