### PR TITLE
Adding import commands

### PR DESCRIPTION
**Pull request by johnsonkuang**
Before, we used bibtex and parsed it in tandem with the umd server to generate publications and talk objects to populate the database.

Now, we take JSON data that we serialized and transferred using the REST API and automatically deserialize using the Django rest_framework. The deserializer will first take the file urls within the JSON and download the files to a temp directory, then sets the file in the JSON wrapped in a Django File Object. Following, the deserialization will deserialize the Many-to-many objects attached to the object (authors, speakers, etc) and save it to the database.

# Testing
To test this command (and ultimately run it) use the following command in the terminal (powershell for windows):
`docker run -ti -v $(pwd)/db:/code/db -v $(pwd)/media:/code/media --entrypoint=python makelab_image manage.py importpubs`

For Windows, it's slightly different, replace the parentheses with curly braces:
`docker run -ti -v ${pwd}/db:/code/db -v ${pwd}/media:/code/media --entrypoint=python makelab_image manage.py importpubs`

## New additions
The previous import command could not properly handle the generation of thumbnails. In addition, temp directories were generated at certain points to contain the downloaded files. There was errors in the code where when we tried to move a file to its new directory, it wasn't there because earlier processes had removed it.

### CODE REVIEW

**Comment by htadeusiak** [comment]
I have an error when I run it. It downloads all the pdf files and then gives me the error. The only publication that is successfully uploaded to my localhost is "BodyVis_A_New_Approach_to_Body_Learning_Through_Wearable_Sensing_and_Visualization_kCJorAs.pdf".

However, I don't think I can give an accurate review. If you remember when I was first setting up my dev environment I kept getting weird warnings when I would use make run. They haven't been an issue up to this point, but I believe my warnings and importpubs are affecting each other now. 

Is there someone else you could have review this for the time being. I believe it would be best for me to meet in person with someone about the errors I keep getting.

Importpubs error:
screen shot 2019-01-02 at 1 17 15 pm
screen shot 2019-01-02 at 1 00 05 pm

Hank's make run errors:
screen shot 2018-12-14 at 9 59 03 am
screen shot 2019-01-02 at 1 24 46 pm

**Comment by jonfroehlich** [comment]
Let me take a quick look on my machine... stay tuned. :)

**Comment by jonfroehlich** [comment]
Hmm, my Docker client on Windows stopped working... this might take me longer than expected.

```
PS D:\tmp\makeabilitylabwebsite> docker build . -t makelab_image
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=9jlzsn99fq4fbf7tlcnkvxd5e&shmsize=0&t=makelab_image&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Comment by jonfroehlich** [comment]
@htadeusiak, in reviewing your screenshots, I don't see any specific errors just some warnings (which I get too) and some DEBUG out statements (which are fine). Is there something that I'm missing from your screenshots?

**Comment by jonfroehlich** [comment]
OK, here's what happened when I ran it on my Mac on a totally clean git checkout.

Looks like it barfed when trying to add a person?

```
Publication 'A Large-Scale Analysis of YouTube Videos Depicting Everyday Thermal Camera Use' has just been saved with PDF=/code/media/publications/import/temp/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.pdf, checking to see if we should auto-generate a thumbnail
DEBUG 2019-01-02 15:43:32,910 utils 1 140486525585152 (0.000) BEGIN; args=None
DEBUG 2019-01-02 15:43:32,926 utils 1 140486525585152 (0.008) UPDATE "website_publication" SET "title" = 'A Large-Scale Analysis of YouTube Videos Depicting Everyday Thermal Camera Use', "pdf_file" = 'publications/import/temp/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.pdf', "book_title" = 'Proceedings of the 20th International Conference on Human-Computer Interaction with Mobile Devices and Services', "book_title_short" = 'Proceedings of MobileHCI 2018', "thumbnail" = 'publications/images/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.jpg', "date" = '2018-09-01', "num_pages" = 12, "page_num_start" = NULL, "page_num_end" = NULL, "official_url" = 'tbd', "geo_location" = 'Barcelona, Spain', "video_id" = NULL, "talk_id" = NULL, "series" = 'MobileHCI ''18', "isbn" = 'tbd', "doi" = 'tbd', "publisher" = NULL, "publisher_address" = 'New York, NY, USA', "acmid" = 'tbd', "pub_venue_type" = 'Conference', "extended_abstract" = NULL, "peer_reviewed" = 1, "total_papers_submitted" = NULL, "total_papers_accepted" = NULL, "award" = NULL WHERE "website_publication"."id" = 1; args=('A Large-Scale Analysis of YouTube Videos Depicting Everyday Thermal Camera Use', 'publications/import/temp/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.pdf', 'Proceedings of the 20th International Conference on Human-Computer Interaction with Mobile Devices and Services', 'Proceedings of MobileHCI 2018', 'publications/images/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.jpg', '2018-09-01', 12, 'tbd', 'Barcelona, Spain', "MobileHCI '18", 'tbd', 'tbd', 'New York, NY, USA', 'tbd', 'Conference', True, 1)
Publication 'A Large-Scale Analysis of YouTube Videos Depicting Everyday Thermal Camera Use' has just been saved with PDF=/code/media/publications/import/temp/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.pdf, checking to see if we should auto-generate a thumbnail
No need to save, the thumbnail '/code/media/publications/images/A_Large-Scale_Analysis_of_YouTube_Videos_Depicting_Everyday_Thermal_Camera_Use.jpg' already exists!
DEBUG 2019-01-02 15:43:32,949 utils 1 140486525585152 (0.003) SELECT "website_person"."id", "website_person"."first_name", "website_person"."middle_name", "website_person"."last_name", "website_person"."url_name", "website_person"."email", "website_person"."personal_website", "website_person"."github", "website_person"."twitter", "website_person"."bio", "website_person"."next_position", "website_person"."next_position_url", "website_person"."image", "website_person"."easter_egg", "website_person"."cropping", "website_person"."easter_egg_crop" FROM "website_person" WHERE ("website_person"."first_name" = 'Mattew' AND "website_person"."last_name" = 'Mauriello') ORDER BY "website_person"."last_name" ASC, "website_person"."first_name" ASC; args=('Mattew', 'Mauriello')
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/importpubs.py", line 188, in handle
    self.loadDatabase(bibtex_str)
  File "/code/website/management/commands/importpubs.py", line 339, in loadDatabase
    author_obj_list = get_authors(author_str_list)
  File "/code/website/management/commands/importpubs.py", line 63, in get_authors
    starwars = get_random_starwars(direc)
  File "/code/website/management/commands/importpubs.py", line 48, in get_random_starwars
    images = [f for f in os.listdir(direc) if isimage(f)]
FileNotFoundError: [Errno 2] No such file or directory: 'import/images/StarWarsFiguresFullSquare/Rebels/'
```

After this error, I ran the website to see how much was there. This is what I found--one pub looks like it was imported (though not all the way):

image

On the Admin interface, you can see that one paper was added:
image

But no people:
image

And if you click on the pub itself in the admin interface, you'll see that authors, projects, keywords, etc. are blank:

image

image

image

**Comment by jonfroehlich** [comment]
> As far as the error, I believe mine is different because I have already created users in the admin interface. Where as you started from a clean slate. But I had the same result of one half way imported publication.

Ah, I see. Well, I think the common use case (and the most important one) is starting from a clean slate. In fact, I don't really care if this doesn't play nice with an existing database of content...

**Comment by jonfroehlich** [comment]
@johnsonkuang, any updates on this?

**Comment by jonfroehlich** [comment]
Hi @johnsonkuang, any updates on this?

**Pull request closed without merging**
