### PR TITLE
428 image files source for readme.md

### PR DESCRIPTION
**Pull request by ghost**
If we were to delete the branch, we need to modify line 86 from 

(https://github.com/jonfroehlich/makeabilitylabwebsite/blob/428-image-files-source-for-readme.md/readme/ConfigureDockerMakingLocalDrivesAvailable.gif)

to 

(https://github.com/jonfroehlich/makeabilitylabwebsite/blob/master/readme/ConfigureDockerMakingLocalDrivesAvailable.gif)

### CODE REVIEW

**Comment by jonfroehlich** [comment]
What do you mean delete the branch?

**Comment by imiao97** [comment]
I thought that if it were to be merged then the branch 428-image-files-source-for-readme.md wont longer be needed. And if it were to be deleted then the url I put for the gif will be gone (in READE.md raw) because the url contain the branch name.

**Comment by htadeusiak** [comment]
I don't think we need both the mp4 and gif files. 

Remove the 'ConfigureDockerMakingLocalDrivesAvailable.mp4' from your commit and then I'll merge your pr.

**Comment by jonfroehlich** [comment]
Closing as outdated

**Pull request closed without merging**
