### PR TITLE
Updated Django and JS Libraries

### LINKED ISSUE #409: Upgrade to newest Django version and JavaScript libraries
We should upgrade to newest version of Django and JavaScript libraries.

### PR DESCRIPTION
**Pull request by johnsonkuang**
This PR resolves #409 #410 #430 and #452 

Summary of changes:

- Moved the Star Wars Figure images into the code/media directory to avoid suspicious file operation errors from Django 2.0 due to media assets being outside the MEDIA_ROOT specified
- Changed the Dockerfile to add the media directory into the docker container so they can be referenced from inside the container
- Added an on_delete parameter to each ForeignKey field, complete list of changes in Issue #410 
> Note that for some fields, the on_delete is set to SET_DEFAULT which depends on a function I wrote that gets a specific person. Currently, that person is set to a person with the last name `Froehlich`; please be sure to have such a person object created before testing this code, or else it'll throw an error. Additionally, this specification could be changed to be more explicit.
- All the requirements in the requirements.txt have been updated to the most recent versions

### CODE REVIEW

**Comment by jonfroehlich** [comment]
> Note that for some fields, the on_delete is set to SET_DEFAULT which depends on a function I wrote that gets a specific person. Currently, that person is set to a person with the last name Froehlich; please be sure to have such a person object created before testing this code, or else it'll throw an error. Additionally, this specification could be changed to be more explicit.

I don't know what this means. Can you clarify?

**Comment by johnsonkuang** [comment]
A default must be specified for the fk fields with on_delete set to default. Right now it’s set to a person object with the last name Froehlich, so the db is required to have such an object to work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonfroehlich** [comment]
> A default must be specified for the fk fields with on_delete set to default. Right now it’s set to a person object with the last name Froehlich, so the db is required to have such an object to work.

Why is this a good idea? I don't understand why you did this. Please provide a more thorough explanation with rationale.

**Comment by johnsonkuang** [comment]
This was done with production in mind, as whenever a person the adviser field is set to is deleted, the adviser will default to the professor.

**Comment by johnsonkuang** [comment]
New commits removes the docker-entrypoint.sh and removes the registered position model from admin

**Pull request merged**
